### ISSUE TITLE
 Facebook domain registration procedure

### ISSUE THREAD

**Issue by ohadsas** [shenkarlab/J14#5]

**Comment by ohadsas** [comment]
Currently pending

**Comment by ohadsas** [comment]
Hi @yonitru and @mushon we still don't have an approval for the production site, this issue is pending for more than a month, we might want to think for another approach.

**Comment by mushon** [comment]
@ohadsas do you need that to be able to use Facebook Connect or are there other ways around it? What are you hoping to get from the API approval and how far can you get without that approval?

**Comment by ohadsas** [comment]
@mushon There is no other way around it.
First we need the Facebook login in order to retrieve users basic info including profile picture and to obtain reliable information from each one.
Second we need to use the Facebook's open-graph protocol - we need to register our site on Facebook's whitelist, this has nothing to do with the first phase, but we can only check this using our production site.

**Comment by mushon** [comment]
Can you work with a mock JSON response for now? Or otherwise, how do you suggest to move forward? @yonitru any suggestions?

**Comment by ohadsas** [comment]
Aborting Facebook.....
